meta_product_name: "TravelMate"
meta_title: "TravelMate - Discover the world with the people around you."
meta_description: "Join up with travel buddies as you explore the world."
meta_image: "ogimage.png" # should exist in `app/assets/images/`
